AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'gemfiles/**/*'
    - 'Appraisals'
Lint/HandleExceptions:
  Exclude:
    - 'spec/support/database.rb'
Style/TrailingCommaInArguments:
  Exclude:
    - '**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
