sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
  - 2.2.9
gemfile:
  - gemfiles/activerecord-3.2.gemfile
  - gemfiles/activerecord-4.2.gemfile
  - gemfiles/activerecord-5.2.gemfile
services:
  - mysql
  - postgresql
before_install:
  - gem install bundler -v 1.16.1
  - mysql -e 'CREATE DATABASE temporarily_test;'
  - psql -c 'CREATE DATABASE temporarily_test;' -U postgres
install: 'bundle install --jobs=3 --retry=3'
